{% set version = "1.2.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-storr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/storr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/storr/storr_{{ version }}.tar.gz
  sha256: c5a76ad87af6d4cd21d26a13422217508cf5d83f608e24688bc136e97fb4eeea

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6 >=2.1.0
    - r-digest
  run:
    - r-base
    - r-r6 >=2.1.0
    - r-digest

test:
  commands:
    - $R -e "library('storr')"           # [not win]
    - "\"%R%\" -e \"library('storr')\""  # [win]

about:
  home: https://github.com/richfitz/storr
  license: MIT
  summary: Creates and manages simple key-value stores.  These can use a variety of approaches for storing the data.  This package implements the base methods and support for file system, in-memory and DBI-based database stores.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
