{% set version = "1.2.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-storr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/storr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/storr/storr_{{ version }}.tar.gz
  sha256: 4224c3991d9c043a45ce530d0698d7f2cdca231b26fe31b45e0db865026e5f63

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6 >=2.1.0
    - r-digest
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-r6 >=2.1.0
    - r-digest

test:
  commands:
    - $R -e "library('storr')"           # [not win]
    - "\"%R%\" -e \"library('storr')\""  # [win]

about:
  home: https://github.com/richfitz/storr
  license: MIT
  summary: Creates and manages simple key-value stores.  These can use a variety of approaches for storing the data.  This package implements the base methods and support for file system, in-memory and DBI-based database stores.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ConorIA
