{% set version = "1.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-storr
  version: {{ version|replace("-", "_") }}

source:
  fn: storr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/storr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/storr/storr_{{ version }}.tar.gz
  sha256: 462a7d738019791440b643a1d6f380c174bde5601c34d666976c44c9cd7a0910

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-r6 >=2.1.0
    - r-digest
  run:
    - r-base
    - r-r6 >=2.1.0
    - r-digest

test:
  commands:
    - $R -e "library('storr')"           # [not win]
    - "\"%R%\" -e \"library('storr')\""  # [win]

about:
  home: https://github.com/richfitz/storr
  license: MIT
  summary: Creates and manages simple key-value stores.  These can use a variety of approaches for storing the data.  This package implements the base methods and support for file system, in-memory and DBI-based database stores.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - ConorIA
