travis:
  secure:
    BINSTAR_TOKEN: D1Yys+CQUHGBakRMlLHGLw31/4/nBDs8KzSBRvVlCSZMXr9De1RI7axeIPOmA1ydUYEZ9rCuqyukL+DJWvDtbifgz0s734v4jtRkI+adgIegshGdwTXvDRHjlUDX4TQZ6Q/IXpS43WWEy5zOewOrl6naUph8xhoDrFnSd2yhm/WZHUDM93SFudcPsGV2Mx720itA5+AoiGY/ld62btRGnCobVoBRk8LYuF9o5BfbsRNDkqQfYnPIQ8rFkEtNDEkRi7ckmM4ekxA47N7vGkvescOpz6XoKpUOe+Q3mucV/v/hj7poUzswhPlGIM1+PXKSwTuREsb8lzFZVCN+sFpT7/lCkEI2T6F4jHUAMZmUd64Ka5RSumOwag9MxswumkjCTqzwro9OLcGUBU1sNk2S4wOeb7ftHEkzjIPbjfaxdEFaq2u5iCo7wHCOWCN8+cD5WK0ASaI+L/VNIInK++/LkUyYo2czVDGHb1pSjE4V4UwXQpXCqrz7z2qREtYE7T76KfS76+4FDrk2o7rUnPbEzD3EJk6TttVptPzsfQbWDtVXDvHGleRAPdBAmes4MfbQ8YqbOyyoaeAY+axSv8ipr6Fd4GqVIMsuApf+rQCO/hovWhE9jsxnzX3BGiu6taojYYoBoIntKmV2b1rP20PqoD4Yyz5qh9nn9irNsDafhXk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
