appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: GXBGKH55LsjPWCx5hMZsYbuZy6SOiAfD4yaTaS7TazMN0tECe6Xsx6bAVVm/LxWqDivk5nriPcZLoiNizBpxr7HMdaCTZ2FEhKX5nBTFbbYFabk6tIdq6A90gJ2ENn63xWXJGimzBDsg4loPBtxxyqA+TUJWL2QpaGyKpZzqGu3PzvUKgZ9CEf/tyWD14GkRGogWiDwSBS+bhB3oZpNPS9b77NzlYEDVeHPuGtAnYHICjLlUylxE3lusfqX1XgmpxU8Hr3ozUtyK119sJfKcn2KMsq66h9a/KWwMsiiAgP5WG4zmRIvu1/noCPiEfd3zyEde+Paqil/d/BToFOTsAviHZBODTFqKwG+Y0mH/ZqWGyoIGsdaiWS0gr1f7sqKo6VatfSQfw/re15hge8pY29u/RLbYHy9xGJfFSWyw3L8ABii9ZmCNQbZiaQuTXZot9DG2yV2BH50fodkCyixbXd6CgO+ER0RjKPRqI8edwosk6hyeC3eG6sZ25VCtPtj4w0logYEcLf6qGQ0Bmp0l67aA0+DLxqacSyVT9EEjCcG4Bksmi7glaZeJ4cQ9BKENAAZmvYqrXHnzy1UdACVcQiYEn5FVnGfOIKXOPp5XtnQCY4a3nPq80l0jieA5OkF0/1a8pJPI7wM5/6C6DyoooC94D0b241RQt0dfXQr9TPs=
conda_forge_output_validation: false
